global:
   scrape_interval: 15s # By default, scrape targets every 15 seconds.

   # Attach these labels to any time series or alerts when communicating with
   # external systems (federation, remote storage, Alertmanager).
   # external_labels:
   #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
   - job_name: "backend"
     static_configs:
        - targets: ["portfolio-backend:5000"]

   - job_name: "prometheus"
     scrape_interval: 5s # Override the global default and scrape targets from this job every 5 seconds.
     static_configs:
        - targets: ["localhost:9090"]

   # node_exporter job
   - job_name: "node_exporter"
     static_configs:
        - targets: ["node_exporter:9100"]

   # cadvisor job
   - job_name: "cadvisor"
     static_configs:
        - targets: ["cadvisor:8080"]
