name: "Render ci-cd pipeline"

on:
   push:
      branches:
         - master

jobs:
   ci-cd-pipeline:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Deploy Server production to Render
           uses: Bounceapp/render-action@0.6.0
           with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              render-token: ${{ secrets.RENDER_AUTH_TOKEN }}
              service-id: ${{ secrets.RENDER_SITE_ID }}
              retries: 20
              wait: 16000
              sleep: 30000
